[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8080

[browser]
gatherUsageStats = false

[theme]
base = "dark"

# fine-tuning
primaryColor = "#7c3aed"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#161b22"
textColor = "#e6edf3"
font = "sans serif"
